// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KidsClub.EFCorePowerTool.Entities
{
    public partial class TblActivityInventory
    {
        public int Id { get; set; }
        public int? ActivityTypeId { get; set; }
        public string Activity { get; set; }
        public string Description { get; set; }
        public byte? ActivityLevel { get; set; }
        public byte? Effort { get; set; }
        public int? QualifyMins { get; set; }
        public bool IsIndoor { get; set; }
        public bool IsOutdoor { get; set; }
        public bool IsActive { get; set; }
        public DateTime DateEntered { get; set; }
    }
}