// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KidsClub.EFCorePowerTool.Entities
{
    public partial class TblMembership
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string MemberName { get; set; }
        public string MembershipType { get; set; }
        public string Rank { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? ExpireDate { get; set; }
        public DateTime DateEntered { get; set; }

        public virtual AspNetUsers User { get; set; }
    }
}