// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace KidsClub.EFCorePowerTool.Entities
{
    public partial class usp_TestimonialsResult
    {
        public int ID { get; set; }
        public int? ParentID { get; set; }
        public int? CategoryID { get; set; }
        public string FromID { get; set; }
        public string ToID { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string URL { get; set; }
        public string URLSlug { get; set; }
        public string Picture { get; set; }
        public string Icon { get; set; }
        public byte? DisplayOrder { get; set; }
        public byte? Qty { get; set; }
        public decimal? Price { get; set; }
        public decimal? DiscountPrice { get; set; }
        public bool isActive { get; set; }
        public bool IsDefault { get; set; }
        public bool IsArchived { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public DateTime? DateUpdated { get; set; }
        public DateTime? DateEntered { get; set; }
    }
}
