// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace KidsClub.EFCorePowerTool.Entities
{
    public partial class usp_EventAttendResult
    {
        public int CategoryID { get; set; }
        public string Category { get; set; }
        public int EventID { get; set; }
        public string EventTitle { get; set; }
        public string EventDescription { get; set; }
        public string EventDetails { get; set; }
        public decimal? EventPrice { get; set; }
        public decimal? EventDiscountedPrice { get; set; }
        public string EventURL { get; set; }
        public string EventPicture { get; set; }
        public string EventLocation { get; set; }
        public DateTime? EventStart { get; set; }
        public DateTime? EventEnd { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public int? Age { get; set; }
        public int? AttendanceID { get; set; }
        public string Note { get; set; }
        public string ShortDescription { get; set; }
        public decimal? Paid { get; set; }
        public DateTime? Arrived { get; set; }
        public DateTime? LeftAt { get; set; }
        public byte? Guests { get; set; }
        public string Picture { get; set; }
    }
}
