// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace KidsClub.EFCorePowerTool.Entities
{
    public partial class usp_Messages_SentResult
    {
    }
}
