// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KidsClub.EFCorePowerTool.Entities
{
    public partial class VwCategoryCount
    {
        public int Expr1 { get; set; }
        public int? Expr2 { get; set; }
        public string Expr3 { get; set; }
        public string Expr4 { get; set; }
        public DateTime Expr5 { get; set; }
        public int? Count { get; set; }
    }
}