// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KidsClub.EFCorePowerTool.Entities
{
    public partial class VwCategoryChild
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int? ChildId { get; set; }
        public int? SubCatAm { get; set; }
        public string Expr1 { get; set; }
    }
}