// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KidsClub.EFCorePowerTool.Entities
{
    public partial class VwContentCategoryFeatures
    {
        public int? Id { get; set; }
        public int? ParentId { get; set; }
        public int? CategoryNumb { get; set; }
        public string CatName { get; set; }
        public string SubCatName { get; set; }
        public int? ChildId { get; set; }
        public int? CountParentId { get; set; }
        public string FromId { get; set; }
        public string ToId { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public int? Likes { get; set; }
        public int? Dislikes { get; set; }
        public string Picture { get; set; }
        public byte? Qty { get; set; }
        public int? SubCatAm { get; set; }
    }
}