// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KidsClub.EFCorePowerTool.Entities
{
    public partial class VwEventAttendance
    {
        public int CategoryId { get; set; }
        public string Category { get; set; }
        public int EventId { get; set; }
        public string EventTitle { get; set; }
        public string EventDescription { get; set; }
        public string EventDetails { get; set; }
        public decimal? EventPrice { get; set; }
        public decimal? EventDiscountedPrice { get; set; }
        public string EventUrl { get; set; }
        public string EventPicture { get; set; }
        public string EventLocation { get; set; }
        public DateTime? EventStart { get; set; }
        public DateTime? EventEnd { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public int? Age { get; set; }
        public int? AttendanceId { get; set; }
        public string Note { get; set; }
        public string ShortDescription { get; set; }
        public decimal? Paid { get; set; }
        public DateTime? Arrived { get; set; }
        public DateTime? LeftAt { get; set; }
        public byte? Guests { get; set; }
        public string Picture { get; set; }
    }
}