// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KidsClub.EFCorePowerTool.Entities
{
    public partial class VwRoleUsers
    {
        public string Name { get; set; }
        public string UserName { get; set; }
    }
}